# Generated by Django 4.2.4 on 2023-09-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='Clave nombre')),
                ('name', models.CharField(max_length=60, verbose_name='Red Social')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace de la red social')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['name'],
            },
        ),
    ]
